{{- if .Values.configs.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- range $key, $val := .Values.configs.all }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end }}



